supporter/config/routes.rb
Rails.application.routes.draw do
  get "/posts"          => "posts#index", as: :back_post
  get "/posts/new"      => "posts#new",     as: :new_post
  post "/posts"         => "posts#create"
  get "/posts/:id"      => "posts#show",    as: :post
  get "/posts/:id/edit" => "posts#edit",    as: :edit_post
  patch "/posts/:id"    => "posts#update"
  delete "/posts/:id"   => "posts#destroy"

  root "posts#index"

end

supporter/app/models/post.rb
class Post < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :department, presence: true
  validates :message, presence: true

 def self.most_recent
    order("created_at DESC")
  end

end

supporter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

supporter/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.most_recent
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def show
  end

  def edit    
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      flash[:alert] = "Failed to update, please try again"
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: "Ticket deleted"
  end

  private

  def find_post
    @post = Post.find params[:id]
  end

  def post_params 
    params.require(:post).
                    permit(:name, :email, 
                            :department, :message)
  end

end

supporter/app/helpers/application_helper.rb
module ApplicationHelper
end

supporter/app/helpers/posts_helper.rb
module PostsHelper
end

supporter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Supporter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= flash[:notice] || flash[:alert] %>
<hr>
<%= yield %>

</body>
</html>

supporter/app/views/posts/_form.html.erb
<% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
<% end %>

<%= form_for @post do |f| %>
  <%= f.label "name*" %>
  <%= f.text_field :name, :size => "33x5" %>
  <br>
  <br>
  <%= f.label "email*" %>
  <%= f.text_field :email, :size => "33x5" %>
  <br>
  <br>
  <%= f.radio_button(:department, "Sales") %>
  <%= f.label :Sales %>
  <%= f.radio_button(:department, "Marketing") %>
  <%= f.label :Marketing %>
  <%= f.radio_button(:department, "Technical") %>
  <%= f.label :Technical %>
  <br>
  <br>
  <%= f.label :Notes %>
  <br>
  <%= f.text_area :message, :size => "35x5" %>
  <br>
  <br>
  <%= f.submit %>
  <br>
  <br>
  <%= link_to "Back To Dashboard", back_post_path(@post) %>
<% end %>

supporter/app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form" %>

supporter/app/views/posts/index.html.erb
<h1>Support Requests</h1>

<%= link_to "Create A New ticket", new_post_path %>
<br>
<ul><p>Name &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Email &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Department &nbsp; &nbsp; &nbsp; &nbsp; Message</p></ul>

<hr>
 <% @posts.each do |p| %>
   <ul><p>
   	<%= p.name %> &nbsp;
   	<%= link_to p.email, post_path(p) %> &nbsp;
   	<%= p.department %> &nbsp;
   	<%= p.message %>
   	&nbsp;
   	<%= link_to "Edit", post_path(p) %>
   	<%= link_to "Delete", method: :delete, data: {confirm: "Are you sure you wish to delete?"} %>
   	<%= button_to "Completed" %>
   </p></ul>
<hr>

<% end %>

supporter/app/views/posts/new.html.erb
<h1>Supporter</h1>
<hr>
<p> Please fill out the following details and a technician will get back to you within 48 hours.</p>
<br>
<br>

<%= render "form" %>

supporter/app/views/posts/show.html.erb
<h1>Ticket Submitted By: &nbsp; <%= @post.name %></h1>

<p>Email: &nbsp; <%= @post.email %></p>
<p>Department: &nbsp; <%= @post.department %></p>
<p>Ticket Details: &nbsp; <%= @post.message %></p>

<%= link_to "Edit", edit_post_path(@post) %> &nbsp;
<%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure you wish to delete?"} %> &nbsp; 
<%= link_to "Back To Dashboard", back_post_path(@post) %>